### ISSUE TITLE
Standardize config ingestion

### ISSUE THREAD

**Issue by galamit86** [dataverbinders/statline-bq#16]
Decide and implement how to ingest configurations, so that we could:

1. Have an immutable structure that holds configurations (ideally "all the way down" the nesting if relevant, but not mandatory)
2. Use dot notation to reach elements
3. Add or remove segments from the config file without adjusting the parsing

**Comment by dkapitan** [comment]
@galamit86 

I have given pyserde a try and it looks good. See [this notebook](https://colab.research.google.com/drive/1t5eqwjHhUhHMCT9r5g_Q1m4Bm4_ngUq_?usp=sharing).

Have posted a question about the best way to write nested toml's:
https://github.com/yukinarit/pyserde/issues/70

**Comment by galamit86** [comment]
@dkapitan 

initial pyserde implementation is [here](https://github.com/dataverbinders/statline-bq/blob/issue_16_standardize_config_input/statline_bq/config.py#L67).

The GCP part is working fine, I think. I am having two separate issues with "Paths" and "Datasets":

_____

1. Paths: As it is currently implemented, we are reading in the whole `config.toml` as a string, then using pyserde to automatically pour it into the predefined classes. As long as everything is a string that's fine, but we would like to have the paths as Path objects, which I am not sure how to do.

I will continue to investigate, if you have a thought - please let me know.

_______
2. Datasets: our general idea so far is allowing to insert a list of datasets within the `config.toml` file, but then to exclude it from the actual config object, and treat it differently then the rest of the config fields (namely Gcp and Paths). I have currently used pyserde `"serde_skip: True"` option when defining the `Config` dataclass, and plan to read only that part of the config file in a separate function, but I am not sure I am happy with this direction, for 2 reasons:

    2.1. Handling different parts of the same file differently feels odd.
    2.2. The `"serde_skip: True"` current implementation still creates a `config.datasets`, which is equal to `['datasets']`, the header text in the toml file. There is a good chance I could implement it differently, and it might work better, but I am not yet sure.

What do you think about removing the datasets from `config.toml` entirely, and adding a `datasets.txt`(or `datasets.toml`) file where this is handled?

* Pro: I believe it addresses the issues I mentioned above, plus it also makes sense for a user to edit datasets list more often than paths or GCP parameters.
* cons: paramaters are defined in 2 different files

**Comment by dkapitan** [comment]
@galamit86 

1. I'd say, let's keep it simple and just use strings as paths in `config.toml` and use Path-objects only in the code
2. +1 for having a separate `datasets.toml`

**Comment by galamit86** [comment]
`pyserde` should be replace with `Box`.
