### ISSUE TITLE
add column descriptions to BQ

### ISSUE THREAD

**Issue by galamit86** [dataverbinders/statline-bq#26]
Load column descriptions of tables in BQ

**Comment by galamit86** [comment]
@dkapitan 
I got sucked into this today, since I think adding column descriptions is a must, or no one will understand anything, and it was (of course) more work than I imagined.

Generally, I think that only the **main table** needs column description, and that is currently implemented for odata v3, with the same logic as I implemented the general dataset description:

1. Get the descriptions from CBS
2. Write them to file (json)
3. Upload to GCS with the rest of the files
4. After creating the dataset in BQ, update the column descriptions for the **main table** (in V3 that is TypedDataset).
_______

Since v4 changes the wide to a long format, I am not sure how the column descriptions fit into there. I need to look into it. 

As usual - if you get a chance to take a look at the [code](https://github.com/dataverbinders/statline-bq/blob/issue_26_add_column_description/statline_bq/utils.py), any input is welcome.

**Comment by dkapitan** [comment]
@galamit
You are right columns descriptions don't make sense in the new structure. I propose to defer that until we decide how to add meta data for the datamarts.

As an aside, I propose to stick to PEP-8 conventions for the sorting of import.
 https://www.python.org/dev/peps/pep-0008/#imports

**Comment by galamit86** [comment]
closed by #34
