### ISSUE TITLE
Add table descriptions

### ISSUE THREAD

**Issue by galamit86** [dataverbinders/statline-bq#6]
Table descriptions are added when script finishes
* Functions to get the table description already exist:  
  * For odata v4 `get_table_description_v4` is in commands.py, but not used
  * For odatat v3 already written in [nimbletl](https://github.com/dataverbinders/nimbletl/blob/7bee9894b45143f315b1a98d70d62c356fb6d70f/nimbletl/tasks.py#L144)
* Where and how to upload the description should be decided and implemented

**Comment by galamit86** [comment]
Best if table descriptions are uploaded to GCS along with the data itself, perhaps as a text file in the same folder. It must be stored in a way that BQ can connect to it as an external dataset.

**Comment by galamit86** [comment]
@dkapitan 
Working on this, I realise we have a bit of mismatch in linguistic definitions when translating from from CBS to GBQ:

* In CBS we call (for example) `"83765NED"` a *Dataset*, and underneath each there are several tables (for example):
  * *83765NED_Observations* 
  * *83765NED_Properties*
  * etc..
* In GCS we call `CBS` a *Schema*
* In GBQ we call `CBS_v4` a *Dataset*, under which there are tables from everything coming from CBS and is version v4 (for example):
  * *83765NED_Observations* 
  * *11111NED_Properties*
  * *2222NED_Observations*

I have 2 issues here, the first relating to this particular issue of adding descriptions text, and the other more general.
________
1. The *Description*, provided by CBS, is the description of a *Dataset ID*, such as `"83765NED"`. In the current way we set it in GBQ, I can see 2 options of where to write this description, none of which I particularly like:
  1.1. In each table with the *Dataset ID*
  1.2. Only in the main table *Observations* (in v3 this would be *TypedDataSet*)
 __________
2. I really do not like having different names for the same things, especially, when they are being passed down from one to the other. Perhaps it is inevitable, but I would like to try and make it better. As the original CBS is what it is, we might consider a different approach in GBQ.

Namely going from:

+--dataverbinders (*Project*)
|---+--cbs_v4 (*Dataset*)
|------+--22222NED_Observations (*Table*)
|------+--22222NED_Properties (*Table*)
|------+--33333NED_Observations (*Table*)
|------+--33333NED_Properties (*Table*)

To:
+--dataverbinders (*Project*)
|---+--cbs_v4_22222NED  (*Dataset*)
|------+--22222NED_Observations (*Table*)
|------+--22222NED_Properties (*Table*)
|---+--cbs_v4_33333NED (*Dataset*)
|------+--33333NED_Observations (*Table*)
|------+--33333NED_Properties (*Table*)

Either way, documenting is important here, to avoid confusion.

**Comment by dkapitan** [comment]
@galamit86 

Good point, no objection do to it the way you propose. So indeed separate datasets in GBQ per CBS dataset.

**Comment by galamit86** [comment]
@dkapitan 
Great, I am going to spend some time to try and make it as consistent as possible for CBS and GBQ (GCS if possible, but less important, I think) and for both v3 and v4.

**Comment by galamit86** [comment]
@dkapitan 
Another tangent question - what was your thinking regarding the nested GCP projects?

I currently explicitly call `config.gcp.dev` when I need to pass GCP parameters in several places, which isn't great, and I imagine was not the idea, but I am not sure what you had in mind.
I can imagine something like adding a `--dev` and `--test` options when running `statline-bq`, is that what you had in mind? If so, I'll add it as a different issue to implement later on.

**Comment by dkapitan** [comment]
@galamit86
Indeed cli options like `--dev` is what I had in mind.

**Comment by galamit86** [comment]
@dkapitan 
How do you feel about these as terms:

* `source`: *'cbs'*
* `odata_version`: *'v3'*
* `dataset`: *'835833NED'* (this can remain `id` in the code, as in the id of this dataset)
* `table`: *'835833NED_MeassureGroups'*
* [Optional] `main_table`: *'835833NED_TypedDataSet'* (for v3) / *'835833NED_Observations (for v4)'*

Do you think I am missing anything? This leaves out `schema` altogether, and I remember Teddy explaining in his paper why you chose that term, but from my (practical and personal) point of view, I find this easier. Open to thoughts.

**Comment by dkapitan** [comment]
@galamit86
More than happy to adopt these terms. `schema` is an older terms from databases, good to leave that out completely.
