### ISSUE TITLE
Add default option to only save parquet files locally, or just load to GCS

### ISSUE THREAD

**Issue by dkapitan** [dataverbinders/statline-bq#73]
Currently parquet files are pushed to GCS and linked in GBQ. Add default option that we only fetch datasets into files which are stored locally.

**Comment by dkapitan** [comment]
@galamit86 
what do you think: worth the effort?

**Comment by galamit86** [comment]
My hunch is yes.
1. It's almost no effort.
2. I wanted to add a `data_to_gcs` option anyway, so we can bundle this together - and then it's really negligent, as the refactoring is done anyway.

what's your use case?

**Comment by galamit86** [comment]
@dkapitan 
So, I ended up implementing a more significant refactoring, and have not addressed the private vs. public methods yet. I think this refactoring might change our approach to it, if we decide to keep it.

* First, I've separated `utils` into 3 modules:

  * `gcpl` module contains the functions that interact with the GCP (named `gcpl` as `gcp` is used in the code already to indicate "google cloud project")
  * `statline` module contains functions that interact with Statline.
  * `utils` module contains generic functions (like `create_dir`, etc.)

* Second, I've added a `main` module, where the higher level functions are defined.

I tried to add order and clarity, but I am not sure if I did. Could you take a look at [this branch](https://github.com/dataverbinders/statline-bq/tree/issue-73-checkpoints/statline_bq) and let me know how you feel about this? Note that the docstrings, especially in `main` are not always up-to-date and sometimes redundant.

___________
Unrelated to this refactoring, I've also added to `main.main()` (previously `utils.main()`) 3 `endpoints` options: `bq`, `gcs` or `local` - to address the actual topic of this issue, and refactored the original `cbsodata_to_gbq`.

**Comment by dkapitan** [comment]
@galamit86 
refactoring makes more sense to me, it is easier to follow now with the separate sub-modules. So no objection to continue along these lines.

**Comment by galamit86** [comment]
@dkapitan 
Nice, glad to hear it.

So for the public/internal division, I propose that only the following functions are public:
* In `statline` module:
  * `get_metadata_cbs`
  * `dataset_to_parquet` (previously named `tables_to_parquet` - doing some house cleaning here)
* In `gcpl` module:
  * `upload_to_gcs`
  * `gcs_to_gbq`
* in `main` module:
  * `main`

Leaving most of our functions as internal - such as all of `utils`, `main.cbsodata_to_[endpoint]`, `gcpl.get_latest_folder`, and more.

I am not sure on which criteria to judge this division - so I figured we keep just the most high level functions in each module. What do you think?

**Comment by dkapitan** [comment]
@galamit86 
There are no hard rules. I think indeed most of the utils functions are private, as are folder checking in gcpl.

But, for example, the clean Python names function can remain public.

Most importantly is that we agree on the minimal set of public functions, for which I agree with your proposal.
